---
title: "punto_corte_segmentado"
author: "Lorena Martínez García"
date: "`r Sys.Date()`"
output: html_document
---

Punto de corte empleando el modelo de regresión segmentada.

```{r}
#Librerías
library(phyloseq)
library(vegan)
library(dplyr)
library(segmented)
```

```{r}
#Función para generar la curva promedio

generar_curva_promedio <- function(phyloseq_obj) {
  # Extraer la tabla OTU del objeto phyloseq
  datos_otu <- as.data.frame(otu_table(phyloseq_obj))
  
  # Generar datos de rarefacción con rarecurve
  datos_curva <- rarecurve(t(datos_otu), step = 50, tidy = TRUE)
  
  # Calcular la curva promedio
  curva_promedio <- datos_rcurva %>%
    group_by(Sample) %>%
    summarize(RiquezaMedia = mean(Species))
  
  return(curva_promedio)
}
```

```{r}
# Curva promedio para cada escenario

curva_promedio_lr <- generar_curva_promedio(phyloseq_object_lr)
curva_promedio_hr <- generar_curva_promedio(physeq_object_hr)
curva_promedio_b <- generar_curva_promedio(phyloseq_object_b)
curva_promedio_u <- generar_curva_promedio(phyloseq_object_u)
```

```{r}
# Función para encontrar automáticamente el punto de corte

encontrar_puntos_quiebre <- function(datos) {
  #  modelo de regresión lineal
  modelo_lineal <- lm(RiquezaMedia ~ Sample, data = datos)
  
  #  Regresión segmentada
  modelo_segmentado <- segmented(modelo_lineal)
  
  # resumen del modelo segmentado
  summary(modelo_segmentado)
  
  # Obtener los puntos de quiebre
  puntos_quiebre <- modelo_segmentado$psi[[2]]
    return(puntos_quiebre)
}

```

```{r}
# Puntos de corte para cada escenario
puntos_quiebre_lr <- encontrar_puntos_quiebre(curva_promedio_lr)
puntos_quiebre_hr <- encontrar_puntos_quiebre(curva_promedio_hr)
puntos_quiebre_b <- encontrar_puntos_quiebre(curva_promedio_b)
puntos_quiebre_u <- encontrar_puntos_quiebre(curva_promedio_u)
```

